cp ./PhytozomeV13/Lusitatissimum/v1.0/annotation/Lusitatissimum*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Slycopersicum/ITAG3.2/annotation/Slycopersicum*ITAG3.2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Athaliana/TAIR10/annotation/Athaliana*TAIR10.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Bdistachyon/v3.1/annotation/Bdistachyon*v3.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Tpratense/v2/annotation/Tpratense*v2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Taestivum/v2.2/annotation/Taestivum*v2.2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Rcommunis/v0.1/annotation/Rcommunis*v0.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Vcarteri/v2.1/annotation/Vcarteri*v2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Slycopersicum/ITAG2.4/annotation/Slycopersicum*ITAG2.4.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Zmarina/v2.2/annotation/Zmarina*v2.2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Osativa/v7.0/annotation/Osativa*v7.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Tcacao/v1.1/annotation/Tcacao*v1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Creinhardtii/v5.5/annotation/Creinhardtii*v5.5.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Macuminata/v1/annotation/Macuminata*v1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Dcarota/v2.0/annotation/Dcarota*v2.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Aofficinalis/V1.1/annotation/Aofficinalis*V1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Mesculenta/v6.1/annotation/Mesculenta*v6.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Cpapaya/ASGPBv0.4/annotation/Cpapaya*ASGPBv0.4.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Fvesca/v2.0.a2/annotation/Fvesca*v2.0.a2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Alyrata/v2.1/annotation/Alyrata*v2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Hannuus/r1.2/annotation/Hannuus*r1.2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Ppatens/v3.3/annotation/Ppatens*v3.3.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Acomosus/v3/annotation/Acomosus*v3.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Sbicolor/v3.1.1/annotation/Sbicolor*v3.1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Stuberosum/v4.03/annotation/Stuberosum*v4.03.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Gmax/Wm82.a2.v1/annotation/Gmax*Wm82.a2.v1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Kfedtschenkoi/v1.1/annotation/Kfedtschenkoi*v1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Sitalica/v2.2/annotation/Sitalica*v2.2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/ZmaysPH207/v1.1/annotation/ZmaysPH207*v1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Cclementina/v1.0/annotation/Cclementina*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Csativus/v1.0/annotation/Csativus*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Czofingiensis/v5.2.3.2/annotation/Czofingiensis*v5.2.3.2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Smoellendorffii/v1.0/annotation/Smoellendorffii*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Hvulgare/r1/annotation/Hvulgare*r1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Ptrichocarpa/v3.1/annotation/Ptrichocarpa*v3.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Csinensis/v1.1/annotation/Csinensis*v1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Ppersica/v2.1/annotation/Ppersica*v2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Athaliana/Araport11/annotation/Athaliana*Araport11.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Vvinifera/v2.1/annotation/Vvinifera*v2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Ahypochondriacus/v2.1/annotation/Ahypochondriacus*v2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Mtruncatula/Mt4.0v1/annotation/Mtruncatula*Mt4.0v1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Mpolymorpha/v3.1/annotation/Mpolymorpha*v3.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Pumbilicalis/v1.5/annotation/Pumbilicalis*v1.5.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Oeuropaea/v1.0/annotation/Oeuropaea*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Cquinoa/v1.0/annotation/Cquinoa*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/CsubellipsoideaC/227 _v2.0/annotation/CsubellipsoideaC*227 _v2.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Esalsugineum/v1.0/annotation/Esalsugineum*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/MpusillaCCMP1545/v3.0/annotation/MpusillaCCMP1545*v3.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Cgrandiflora/v1.1/annotation/Cgrandiflora*v1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Egrandis/v2.0/annotation/Egrandis*v2.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Creinhardtii/v5.6/annotation/Creinhardtii*v5.6.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Spolyrhiza/v2/annotation/Spolyrhiza*v2.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Gmax/Wm82.a4.v1/annotation/Gmax*Wm82.a4.v1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Atrichopoda/v1.0/annotation/Atrichopoda*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Olucimarinus/v2.0/annotation/Olucimarinus*v2.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Zmays/RefGen _V4/annotation/Zmays*RefGen _V4.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Lsativa/V8/annotation/Lsativa*V8.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/MspRCC299/v3.0/annotation/MspRCC299*v3.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Graimondii/v2.1/annotation/Graimondii*v2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Othomaeum/v1.0/annotation/Othomaeum*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Mguttatus/v2.0/annotation/Mguttatus*v2.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Boleraceacapitata/v1.0/annotation/Boleraceacapitata*v1.0.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd21v2_1/v2.1/annotation/BdistachyonBd21v2_1*v2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd21_3/v1.Bd21_3_r.1/annotation/BdistachyonBd21_3*v1.Bd21_3_r.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonABR2/v1.ABR2.1/annotation/BdistachyonABR2*v1.ABR2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonABR3/v1.ABR3.1/annotation/BdistachyonABR3*v1.ABR3.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonABR4/v1.ABR4.1/annotation/BdistachyonABR4*v1.ABR4.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonABR5/v1.ABR5.1/annotation/BdistachyonABR5*v1.ABR5.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonABR6/v1.ABR6/annotation/BdistachyonABR6*v1.ABR6.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonABR7/v1.ABR7.1/annotation/BdistachyonABR7*v1.ABR7.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonABR8/v1.ABR8.1/annotation/BdistachyonABR8*v1.ABR8.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonABR9/v1.ABR9/annotation/BdistachyonABR9*v1.ABR9.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonAdi_10/v1.Adi_10.1/annotation/BdistachyonAdi_10*v1.Adi_10.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonAdi_12/v1.Adi_12.1/annotation/BdistachyonAdi_12*v1.Adi_12.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonAdi_2/v1.Adi_2.1/annotation/BdistachyonAdi_2*v1.Adi_2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonArn1/v1.Arn1.1/annotation/BdistachyonArn1*v1.Arn1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd1_1/v1.Bd1_1.1/annotation/BdistachyonBd1_1*v1.Bd1_1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd18_1/v1.Bd18_1.1/annotation/BdistachyonBd18_1*v1.Bd18_1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd2_3/v1.Bd2_3.1/annotation/BdistachyonBd2_3*v1.Bd2_3.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd21AnntCtrl/Bd21AnntCtrl/annotation/BdistachyonBd21AnntCtrl*Bd21AnntCtrl.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd21AsmbCtrl/Bd21AsmbCtrl/annotation/BdistachyonBd21AsmbCtrl*Bd21AsmbCtrl.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd29_1/v1.Bd29_1.1/annotation/BdistachyonBd29_1*v1.Bd29_1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd3_1/v1.Bd3_1.1/annotation/BdistachyonBd3_1*v1.Bd3_1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBd30_1/v1.Bd30_1.1/annotation/BdistachyonBd30_1*v1.Bd30_1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR10c/v1.BdTR10C.1/annotation/BdistachyonBdTR10c*v1.BdTR10C.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR11a/v1.BdTR11A.1/annotation/BdistachyonBdTR11a*v1.BdTR11A.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR11g/v1.BdTR11G.1/annotation/BdistachyonBdTR11g*v1.BdTR11G.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR11i/v1.BdTR11I.1/annotation/BdistachyonBdTR11i*v1.BdTR11I.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR12c/v1.BdTR12c.1/annotation/BdistachyonBdTR12c*v1.BdTR12c.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR13a/v1.BdTR13a.1/annotation/BdistachyonBdTR13a*v1.BdTR13a.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR13c/v1.BdTR13C.1/annotation/BdistachyonBdTR13c*v1.BdTR13C.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR1i/v1.BdTR1i.1/annotation/BdistachyonBdTR1i*v1.BdTR1i.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR2b/v1.BdTR2B.1/annotation/BdistachyonBdTR2b*v1.BdTR2B.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR2g/v1.BdTR2G.1/annotation/BdistachyonBdTR2g*v1.BdTR2G.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR3c/v1.BdTR3C.1/annotation/BdistachyonBdTR3c*v1.BdTR3C.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR5i/v1.BdTR5I.1/annotation/BdistachyonBdTR5i*v1.BdTR5I.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR7a/v1.BdTR7a.1/annotation/BdistachyonBdTR7a*v1.BdTR7a.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR8i/v1.BdTR8i.1/annotation/BdistachyonBdTR8i*v1.BdTR8i.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBdTR9k/v1.BdTR9K.1/annotation/BdistachyonBdTR9k*v1.BdTR9K.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonBis_1/v1.Bis_1.1/annotation/BdistachyonBis_1*v1.Bis_1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonFoz1/v1.Foz1.1/annotation/BdistachyonFoz1*v1.Foz1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonGaz_8/v1.Gaz_8.1/annotation/BdistachyonGaz_8*v1.Gaz_8.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonJer1/v1.Jer1.1/annotation/BdistachyonJer1*v1.Jer1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonKah_1/v1.Kah_1.1/annotation/BdistachyonKah_1*v1.Kah_1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonKah_5/v1.Kah_5.1/annotation/BdistachyonKah_5*v1.Kah_5.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonKoz_1/v1.Koz_1.1/annotation/BdistachyonKoz_1*v1.Koz_1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonKoz_3/v1.Koz_3.1/annotation/BdistachyonKoz_3*v1.Koz_3.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonLuc1/v1.Luc1.1/annotation/BdistachyonLuc1*v1.Luc1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonMig3/v1.Mig3.1/annotation/BdistachyonMig3*v1.Mig3.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonMon3/v1.Mon3.1/annotation/BdistachyonMon3*v1.Mon3.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonMur1/v1.Mur1.1/annotation/BdistachyonMur1*v1.Mur1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonPer1/v1.Per1.1/annotation/BdistachyonPer1*v1.Per1.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonRon2/v1.RON2.1/annotation/BdistachyonRon2*v1.RON2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonSig2/v1.Sig2.1/annotation/BdistachyonSig2*v1.Sig2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonTek_2/v1.Tek_2.1/annotation/BdistachyonTek_2*v1.Tek_2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonTek_4/v1.Tek_4.1/annotation/BdistachyonTek_4*v1.Tek_4.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/BdistachyonUni2/v1.Uni2.1/annotation/BdistachyonUni2*v1.Uni2.1.protein.fa.gz ./phytoPep
cp ./PhytozomeV13/Bdistachyonpangenome/v1.pangenome.1/annotation/Bdistachyonpangenome*v1.pangenome.1.protein.fa.gz ./phytoPep
